os: osx
go: 1.12.x
language: go
jobs:
  include:
    - stage: "Build SMLogs"
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod
      env:
        - GO111MODULE=on
      script:
        - make
        - cd smlogs-kubectl-plugin && make build-release

    - stage: "Test"
      name: "Run Integration Tests"
      script:
        - echo "Here is where we do the testing"